support for itunes episode & season
ruby/rss pull request #31
Opened 2021-04-28 18:08 UTC by saerdnaer

2021-04-29 09:57 UTC, olleolleolle commented
I was able to locate the information about Apple's podcasting RSS requirements: https://help.apple.com/itc/podcasts_connect/#/itcb54353390

2021-04-29 09:58 UTC, olleolleolle requested changes
I saw two tiny typos when running the CI job.

Cool feature.

2021-04-29 09:58 UTC, olleolleolle commented on test/test-itunes.rb
> +      assert_assert_itunes_season(%w(channel)) do |content, xmlns|
```suggestion
      assert_itunes_season(%w(channel)) do |content, xmlns|
```

2021-04-29 09:58 UTC, olleolleolle commented on test/test-itunes.rb
> +      assert_assert_itunes_episode(%w(channel)) do |content, xmlns|
```suggestion
      assert_itunes_episode(%w(channel)) do |content, xmlns|
```

2021-04-29 21:19 UTC, kou commented
It seems that both of `<itunes:episode>` and `<itunes:season>` should exist in `item` not `channel`.

It seems that both of them needs validation (a non-zero integer). Do you want me to take over it?

2021-05-01 13:15 UTC, saerdnaer commented
@kou Yes thats, right. Feel free to take it over.

2021-05-03 05:40 UTC, merged

2021-05-03 05:41 UTC, kou commented
I've fixed a bug that `channel` still parses `episode` and `season`.
I've also added non zero positive integer validation.

I've merged. Thanks.